[package]
name = "advent-of-code-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
ahash = { version = "0.8" }
fnv = { version = "1" }
sscanf = { version = "0.4" }
rayon = { version = "1" }
